# Generated by Django 3.2.9 on 2021-12-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='empty.jpg', null=True, upload_to=''),
        ),
    ]
