# Generated by Django 4.0 on 2021-12-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_soldproducts_purchasedproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='purchasedproducts',
            name='image',
            field=models.ImageField(blank=True, default='empty.jpg', null=True, upload_to=''),
        ),
    ]
