# Generated by Django 4.0 on 2021-12-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_image_alter_purchasedproducts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='empty.jpg', null=True, upload_to='media'),
        ),
    ]
